server:
  port: 8080

spring:
  application:
    name: 'jahongir-me'

  datasource:
    username: 'postgres'
    password: '123'
    driver-class-name: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5432/jahongir_pay'

  jpa:
    hibernate:
      ddl-auto: update

bot:
  username: 'your_bot_username'
  token: 'your_bot_api_token'